### PR TITLE
Use a single tab field separator in keywords.txt

### PR DESCRIPTION
**Pull request by per1234**
Each field of keywords.txt is separated by a single true tab. When you use multiple tabs it causes the field to be interpreted as empty. On Arduino IDE 1.6.5 and newer an empty KEYWORD_TOKENTYPE causes the default editor.function.style coloration to be used (as with KEYWORD2, KEYWORD3, LITERAL2). On Arduino IDE 1.6.4 and older it causes the keyword to not be recognized for any special coloration.

Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords

### CODE REVIEW

**Comment by per1234** [comment]
@Trusty77 if you want to reproduce my work ([only in a non-atomic manner with a crap commit message](https://github.com/Locoduino/Commanders/commit/0845072ff5d3e7fe827007a62836bfb7e2546922)) that's your prerogative, but it would only be considerate to take a few seconds to comment on the pull request to explain why it was closed. Otherwise I must waste time looking through the repository to try to figure out what happened. This is not a very nice way to treat someone trying to contribute to your projects.

**Comment by Trusty77** [comment]
Work has been done on all my libraries.

**Comment by per1234** [comment]
What's that supposed to mean?

**Comment by Trusty77** [comment]
Exactly what i wrote : i have propagated the fix in all my libraries. Thank you for your attention.

**Comment by per1234** [comment]
OK, I understand what you meant. I'm glad if my work has been useful.

**Pull request closed without merging**
